### ISSUE TITLE
Start year and end year parameters not being respected

### ISSUE THREAD

**Issue by jdbcode** [jdbcode/ee-rgb-timeseries#2]
[via email to @jdbcode]

I have been using this module to look at the NDVI time series of some fire sites I studied in the Northwest Territories. I am trying to run the Landsat example, but I seem to be having some problems setting the ee-lcb parameters. I am interested in extracting only the data from 2010-2020. For some reason, regardless of how I change the start/end year, I am still always getting 1984-2018. I have included a screenshot below. The code is line-for-line the same as your example. 

![image](https://user-images.githubusercontent.com/9044197/112761326-a417bd00-8faf-11eb-875f-171be0734591.png)

**Comment by jdbcode** [comment]
I can't reproduce the problem. If I change the start and end year, the chart reflects the change (see image). I know you said the script is line-for-line the same, but can you send me the script link so I can try to reproduce the issue.

![image](https://user-images.githubusercontent.com/9044197/112761399-fa84fb80-8faf-11eb-81f6-442d60e4b150.png)

**Comment by arangech** [comment]
Hi Justin, [here's](https://code.earthengine.google.com/1795518a7c02eae12965521895b326c1) the script link. 
![GEE_RGB_TS](https://user-images.githubusercontent.com/35582892/112774177-a567da80-8fed-11eb-826e-a6abcb9cd466.PNG)

Edit: Updated link to public repository

**Comment by jdbcode** [comment]
This is strange. The fix is to define a `props` variable resulting from the `lcb.setProps` call and when `lcb` props are needed, retrieve them with `props.propertyName` instead of `lcb.props.propertyName`. I can't figure out I could not reproduce. Anyway here is your script with the changes:

https://code.earthengine.google.com/037107c9d1d958f59da5ce591e6f2df6

I'm going to keep this open for a while until I can figure out why I could not reproduce.

I have fixed the example on the readme page.

**Comment by jdbcode** [comment]
Note that the root of the issue is with the required `ee-lcb` module: https://github.com/jdbcode/EE-LCB, not the this `rgb-timeseries` module

**Comment by arangech** [comment]
> This is strange. The fix is to define a `props` variable resulting from the `lcb.setProps` call and when `lcb` props are needed, retrieve them with `props.propertyName` instead of `lcb.props.propertyName`. I can't figure out I could not reproduce. Anyway here is your script with the changes:
> 
> https://code.earthengine.google.com/037107c9d1d958f59da5ce591e6f2df6
> 
> I'm going to keep this open for a while until I can figure out why I could not reproduce.
> 
> I have fixed the example on the readme page.

Thanks. This works for me now with the props variable defined.

**Comment by jdbcode** [comment]
Not using the ee-lcb module anymore - this particular issue is not relevant anymore.
