### ISSUE TITLE
ee.Number.clamp is not a function

### ISSUE THREAD

**Issue by Yiuky** [jdbcode/ee-rgb-timeseries#3]
While in test, this error raised days ago.

![ERRO](https://user-images.githubusercontent.com/17982478/118521794-5dba2100-b709-11eb-8188-9c3e920c5b5e.PNG)

**Comment by jdbcode** [comment]
Thanks for letting me know! I'm looking into it.

**Comment by jdbcode** [comment]
Fixed! The API's `ee.Number.clamp` method changed

before fix implemented:
`val = ee.Number.clamp(val, min, max);`

after fix implemented:
`val = ee.Number(val).clamp(min, max);`

I really appreciate the heads up - thank you!
