### ISSUE TITLE
TimeSeries App does not include year 2022

### ISSUE THREAD

**Issue by igorcunhaperez** [jdbcode/ee-rgb-timeseries#5]
Hello Justin.

I've been using the Landsat-8 Image Time series app a lot and I really like it. I would like to evaluate Landsat images from the year 2022, but the APP only provides the time series up to the year 2021.

![Captura](https://user-images.githubusercontent.com/59975253/213219886-b02b17f6-b170-4589-9a6a-3099ea06abd2.JPG)

Could you help me with this problem? I have tried in many ways, but to no avail.

I'm from Brazil and I work with monitoring of the Amazon rainforest

I hope you can help me!

Best Regards

Igor. P

**Comment by alkirschbaum** [comment]
I think the issue is that the app is pulling from Landsat Collection 1.
https://developers.google.com/earth-engine/datasets/catalog/landsat

**Comment by tglass5** [comment]
I'd like to echo Igor P. and express a big thanks for this great resource. It seems like the app is still only pulling through 2021, though - any plans to migrate it to Landsat Collection 2, assuming that is the issue?

Thanks,
Tom

**Comment by jdbcode** [comment]
Hello Igor, Al, and Tom! Sorry for the delay. Yes, the issue is that the App is still using Collection 1. I'm hoping to get it migrated to Collection 2 within the next week or so. I'll ping this thread when it is ready.

**Comment by tglass5** [comment]
Thanks for your quick reply and attention to it!

**Comment by jdbcode** [comment]
Hi all, I've updated the app to use Landsat Collection 2. Note that I removed the tasselled cap indices (might add them back later, but wanted results returned as fast as possible). Also, the band names are now wavelength range names instead of e.g., B2, B3. I need to change visualization parameters too, so there could slight difference in color appearance.
